server:
  port: 8835

spring:
  mvc:
    servlet:
      path: /pcs/system
  profiles:
    active: auth,database
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 1655447052@qq.com
    password: wmjucpizwhgweejd
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

knife4j:
  enable: true
  setting:
    language: zh_cn