sa-token:
  # Token validity period (in seconds). Default is 30 days. -1 means it is permanently valid.
  #  timeout: 43200
  # For tokens that can be automatically renewed, how long after an idle operation will they expire.
  active-timeout: 43200
  # Whether to allow simultaneous logins of the same account from multiple locations (true allows simultaneous login, false makes new logins kick out the old ones).
  is-concurrent: true
  # When multiple users log into the same account, whether they share a single token (true means all logins share one token, false means a new token is created for each login).
  is-share: true
  # Token style (default values available: uuid, simple-uuid, random-32, random-64, random-128, tik).
  token-style: uuid
  # Whether to output operation logs.
  is-log: true
  jwt-secret-key: 626972AE8B057DD3A3D2914A7C1210B2
  token-name: yzxToken

# Configuration without a global request prefix
whitelist:
  urls:
    - /**/user/login
    - /auth/user/login/verification/code
    - /**/user/register
    - /v3/api-docs/**
    - /swagger-ui/**/*.*
    - /favicon.ico
    - /webjars/**
    - /*.html
    - /auth/user/genQr

publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvz8UdLTOtEBx0qQG8ChCxJqzHrpsjKqulFlJbE9qssJTDrXxwaIa5xpTUSyQgveW5SQvzJNVzDHVgPxPrR8O47xNgordPzF2ugz5WrjsH6NY8+VpZKVVW+IbjqH5extMrdWDKGri/CqNDkO00symGa+Ms24wO1CpGwIyexMoinoV7Dl3FIufbCE8XFk1BcBgyg0ZWJMVmNleaESmUI6Jmen92wcLP3XqE22zaCuODqJWi2jT4ePI05KyFQrGE9tD2P8lmTB8BbAXGx42aHAzXVDGSMWefpA6IZRC2148R9+hbEYvseS4JecOfZnjqciZXbkDckoGpl/fFZN3oQIo/wIDAQAB
privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/PxR0tM60QHHSpAbwKELEmrMeumyMqq6UWUlsT2qywlMOtfHBohrnGlNRLJCC95blJC/Mk1XMMdWA/E+tHw7jvE2Cit0/MXa6DPlauOwfo1jz5WlkpVVb4huOofl7G0yt1YMoauL8Ko0OQ7TSzKYZr4yzbjA7UKkbAjJ7EyiKehXsOXcUi59sITxcWTUFwGDKDRlYkxWY2V5oRKZQjomZ6f3bBws/deoTbbNoK44OolaLaNPh48jTkrIVCsYT20PY/yWZMHwFsBcbHjZocDNdUMZIxZ5+kDohlELbXjxH36FsRi+x5Lgl5w59meOpyJlduQNySgamX98Vk3ehAij/AgMBAAECggEAHRdKVEpgmviml8UNrSBir6dckdMHygn4jm​⬤